### ISSUE TITLE
Markdown dosyasındaki yanlış lisans bağlantısı

### ISSUE THREAD

**Issue by mertssmnoglu** [cesii/thetan-arena-clone#1]
Markdown dosyasının [56. satırında](https://github.com/cesii/thetan-arena-clone/blob/main/README.md?plain=1#L56) LİSANS olarak belirtilen dosya aslında `./LICENSE` olursa link doğru olacaktır.

**Comment by cesii** [comment]
çok sağol mert, düzelttim 😅

**Comment by mertssmnoglu** [comment]
Rica ederim ne demek. Başarılar :rocket:
